baseURL = "https://tucsonfoodshare.org/"
title = "Tucson Food Share"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    weight = 1
    languageCode = "en-US"
    languageName = "English"
    contentDir = "content/en"

  [languages.es]
    weight = 2
    languageCode = "es"
    languageName = "Español"
    contentDir = "content/es"
    title = "Tucson Food Share"

[taxonomies]

[markup.goldmark.renderer]
  unsafe = true
